# Generated by Django 5.2.6 on 2025-10-01 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='proof_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_proof',
            field=models.CharField(default='Aadhaar', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
