# Generated by Django 5.2.6 on 2025-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_proof_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='face_encoding',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='face_image',
            field=models.ImageField(default='default.jpg', upload_to='faces/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_proof',
            field=models.CharField(max_length=50),
        ),
    ]
