# Generated by Django 5.2.6 on 2025-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_face_encoding_alter_customer_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
